services:
  web:
    image: ghcr.io/anjarhariadi/risetunik-web:latest
    container_name: risetunik-web
    ports:
      - "3030:80"
    restart: always
    depends_on:
      - server

  server:
    image: ghcr.io/anjarhariadi/risetunik-server:latest
    container_name: risetunik-server
    ports:
      - "3031:8000"
    env_file:
      - ./server/.env
    restart: always
